name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] 
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: .NET SDK
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '5.0.100'
    - name: Build
      run: pwsh ./build.ps1